# Generated by Django 5.2 on 2025-07-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_details',
            new_name='EventDetails',
        ),
    ]
